print('My name is Hannah')
print("I was born in July")
print('My favorite food is Chocolate')
print('My favorite type of music is pop')
print('im a cancer')
print('rosner')

print('My name is Danielle')
print('I was born in June')
print('I like pop music')
print('Gemini')
print('My moms maiden name is Ruderman')
